config:
  MD013:
    line_length: 100
    tables: false
  MD055:
    style: leading_and_trailing
  MD060:
    style: aligned
    aligned_delimiter: true
  MD033:
    allowed_elements:
      - a
      - Card
      - CardGrid
      - div
      - footer
      - h1
      - h2
      - img
      - kbd
      - nav
      - p
      - polygon
      - rect
      - section
      - span
      - svg
  MD024:
    siblings_only: true
