config:
  MD013:
    line_length: 100
    tables: false
  MD055:
    style: leading_and_trailing
  MD060:
    style: aligned
    aligned_delimiter: true
  MD033:
    allowed_elements:
      - a
      - aside
      - Card
      - CardGrid
      - code
      - div
      - footer
      - h1
      - h2
      - img
      - kbd
      - li
      - nav
      - p
      - polygon
      - rect
      - section
      - small
      - span
      - strong
      - svg
      - table
      - tbody
      - td
      - th
      - thead
      - tr
      - ul
  MD024:
    siblings_only: true
